  sudo: required
  services:
    - docker

  before_install:
    - docker build -t cengo/multi-dockeronaws -f ./client/Dockerfile.dev ./client
  
  script: 
    -  docker run -e CI=true cengo/multi-dockeronaws yarn test -- --coverage
  
  after_success:
    - docker build -t cengo/multi-client ./client
    - docker build -t cengo/multi-nginx ./nginx
    - docker build -t cengo/multi-server ./server
    - docker build -t cengo/multi-worker ./worker
  ## Push these created images to the docker-hub 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## Login to the docker-cli
    - docker push cengo/multi-client
    - docker push cengo/multi-nginx
    - docker push cengo/multi-server
    - docker push cengo/multi-worker
  ## Deploy the application
  deploy:
    provider: elasticbeantalk
    region: us-east-2
    app: docker
    env: Docker-multi-env 
    bucket_name: elasticbeanstalk-us-east-2-416358073398
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: 
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY